name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  main:
    name: âš™ï¸ Build Packages
    strategy:
      matrix:
        # TODO: relax `'16.9.1'` to `16` once GitHub has 16.9.1 cached. 16.9.0 is broken due to https://github.com/nodejs/node/issues/40030
        node: [12, 14, '16.9.1']
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v2

      - name: â” Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org

      - name: â¬‡ï¸ Install Dependencies
        run: yarn --frozen-lockfile

      - name: ğŸ“‹ Format Check
        run: yarn format --check

      - name: ğŸ“‹ Eslint
        run: yarn lint

      - name: ğŸ— Build
        run: yarn build

      - name: ğŸ§ª Run Tests
        run: yarn test

      - name: ğŸ“— Build Storybook
        run: yarn build-storybook
      
      # - name: ğŸš€ Deploy
      # will be implemented in future
